import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const script = fileURLToPath(new URL('../scripts/kubernetes-helm-lab.sh', import.meta.url))

test('Kubernetes Helm lab is valid Bash and uses ephemeral guarded node executors', () => {
  execFileSync('bash', ['-n', script])
  const help = execFileSync('bash', [script, 'help'], { encoding: 'utf8' })
  const source = readFileSync(script, 'utf8')

  assert.match(help, /three-node kind cluster/)
  assert.match(help, /without Netdata or a\nIntent AI Ops plugin/)
  assert.match(help, /docker, kind, kubectl, helm, curl/)
  assert.match(help, /bootstrap\s+Install the required host tools on Ubuntu 26\.04/)
  assert.match(help, /monitoring-remove \[--yes\]/)
  assert.match(help, /container-kubeconfig/)
  assert.match(help, /container-network-up/)
  assert.match(help, /container-network-down/)
  assert.match(help, /container-route-up/)
  assert.match(help, /container-route-down/)
  assert.match(help, /equivalent to root on each selected node/)
  assert.equal((source.match(/- role: worker/g) ?? []).length, 2)
  assert.match(source, /https:\/\/netdata\.github\.io\/helmchart\//)
  assert.match(source, /https:\/\/pkgs\.k8s\.io\/core:\/stable:/)
  assert.match(source, /packages\.buildkite\.com\/helm-linux\/helm-debian/)
  assert.match(source, /\$kind_name\.sha256sum/)
  assert.match(source, /apt-get install -y docker\.io/)
  assert.match(source, /upgrade --install "\$NETDATA_RELEASE" netdata\/netdata/)
  assert.match(source, /up_lab\(\)[\s\S]*install_sample_workload[\s\S]*verify_base_lab/)
  const upLab = source.match(/up_lab\(\) \{([\s\S]*?)\n\}/)?.[1] ?? ''
  assert.doesNotMatch(upLab, /install_netdata/)
  assert.match(source, /remove_monitoring_resources/)
  assert.match(source, /kind get kubeconfig --name "\$CLUSTER_NAME" --internal/)
  assert.match(source, /chmod 0600 "\$temporary_file"/)
  assert.match(source, /Do not mount the Docker socket/)
  assert.match(source, /docker network connect kind/)
  assert.match(source, /docker network disconnect kind/)
  assert.match(source, /No container or cluster recreation was required/)
  assert.match(source, /WEBMINAI_K8S_CLIENT_IP/)
  assert.match(source, /iptables -w 5 -I DOCKER-USER 1/)
  assert.match(source, /iptables -w 5 -I FORWARD 1/)
  assert.match(source, /iptables -w 5 -t nat -I POSTROUTING 1/)
  assert.match(source, /--dport 6443 -j MASQUERADE/)
  assert.match(source, /iptables -w 5 -t nat -D POSTROUTING/)
  assert.match(source, /route_interface/)
  assert.match(source, /for \(field = 1; field <= NF; field\+\+\)/)
  assert.doesNotMatch(source, /for \(index = 1; index <= NF; index\+\+\)/)
  assert.match(source, /--dport 6443/)
  assert.match(source, /--sport 6443/)
  assert.match(source, /iptables -w 5 -D DOCKER-USER/)
  assert.match(source, /KUBECONFIG="\$temporary_file" kubectl get nodes/)
  assert.match(source, /no SSH server is used/)
  assert.match(source, /database:/)
  assert.match(source, /persistence: false/)
  assert.match(source, /api\/v3\/info\?options=full/)
  assert.match(source, /\/api\/v1\/info/)
  assert.match(source, /port-forward --address 127\.0\.0\.1/)
  assert.match(source, /deployment\/\$NETDATA_RELEASE-parent/)
  assert.match(source, /mapfile -t workloads/)
  assert.match(source, /rollout status "\$workload"/)
  assert.doesNotMatch(source, /rollout status (deployment|daemonset) --all/)
  assert.match(source, /nodeName: \$node/)
  assert.match(source, /hostPID: true/)
  assert.match(source, /privileged: true/)
  assert.match(source, /hostPath:\n\s+path: \//)
  assert.match(source, /kind: ServiceAccount/)
  assert.match(source, /name: webminai-stage2-gateway/)
  assert.match(source, /kubectl_gateway apply -f -/)
  assert.match(source, /auth can-i create daemonsets\.apps/)
  assert.match(source, /gateway service account must not create DaemonSets/)
  assert.match(source, /delete jobs .*webminai\.io\/execution=ephemeral-node-test/)
  assert.match(source, /unexpected persistent executor DaemonSet exists/)
  assert.match(source, /assert_marker/)
  assert.match(source, /kind delete cluster --name "\$CLUSTER_NAME"/)
})
