import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const installer = fileURLToPath(new URL('../remote/webminai-stage2.sh', import.meta.url))
const windowsInstaller = fileURLToPath(new URL('../remote/webminai-stage2-windows.ps1', import.meta.url))

test('stage 2 installs a setuid root plugin and a root-only host token', async () => {
  const source = await readFile(installer, 'utf8')
  assert.match(source, /install -o root -g "\$NETDATA_GROUP" -m 4750 "\$plugin_source"/)
  assert.match(source, /Linux\)\n {4}PLATFORM_ID=linux\n {4}ROOT_GROUP=root\n {4}NETDATA_GROUP=netdata/)
  assert.match(source, /chown root:"\$NETDATA_GROUP" "\$config_file"/)
  assert.match(source, /chmod 0640 "\$config_file"/)
  assert.match(source, /ROOT_GROUP=wheel/)
  assert.match(source, /FreeBSD\)\n {4}PLATFORM_ID=freebsd\n {4}ROOT_GROUP=wheel\n {4}NETDATA_GROUP=netdata/)
  assert.match(source, /chown root:"\$ROOT_GROUP" "\$KEY_FILE"/)
  assert.match(source, /chmod 0600 "\$KEY_FILE"/)
  assert.match(source, /plugin_action=unchanged/)
  assert.match(source, /"\$STATE_DIR\/plugin-version"/)
  assert.match(source, /"pluginAction":"%s","pluginVersion":"%s"/)
  assert.match(source, /rollback_activation\(\)/)
  assert.match(source, /"\$STATE_DIR\/plugin-backup"/)
  assert.match(source, /claim_cloud\(\)/)
  assert.match(source, /chown root:netdata "\$temporary_claim"/)
  assert.match(source, /chmod 0640 "\$temporary_claim"/)
  assert.match(source, /reload-claiming-state/)
  assert.match(source, /FreeBSD\)/)
  assert.match(source, /STATE_DIR=\/var\/db\/webminai/)
  assert.match(source, /\/usr\/local\/etc\/netdata/)
  assert.match(source, /\/usr\/local\/libexec\/netdata\/plugins\.d/)
  assert.match(source, /service netdata onerestart/)
  assert.match(source, /pgrep -x netdata/)
  assert.match(source, /ASSUME_ALWAYS_YES=yes pkg install -y/)
  assert.match(source, /pkg install -y netdata/)
  assert.match(source, /pkg delete -y netdata/)
  assert.match(source, /install Netdata manually, then use plugin-only activation/)
  assert.match(source, /pkg install -y netdata\n {4}mkdir -p "\$STATE_DIR"\n {4}chmod 0700 "\$STATE_DIR"\n {4}: > "\$STATE_DIR\/netdata-owned"/)
  assert.match(source, /find_homebrew\(\)/)
  assert.match(source, /find_homebrew_owner\(\)/)
  assert.match(source, /'\$brew_path' install netdata/)
  assert.match(source, /'\$brew_path' uninstall --force netdata/)
  assert.match(source, /if \[ "\$status" = inactive \] && \[ "\$ownership" = managed \]; then/)
  assert.match(source, /plugin artifact platform mismatch/)
  assert.match(source, /"platform":"%s"/)
  assert.match(source, /cancel_webminai_jobs\(\)/)
  assert.match(source, /kill -TERM "-\$job_pid"/)
  assert.match(source, /rm -rf -- "\$job_root"/)
  assert.match(source, /cancel_webminai_jobs\n {2}rm -f "\$KEY_FILE"/)
  assert.match(source, /NETDATA_ROOT_PLUGIN_DROPIN=\/etc\/systemd\/system\/netdata\.service\.d\/webminai-root-plugin\.conf/)
  assert.match(source, /configure_root_plugin_service\(\)/)
  assert.match(source, /CapabilityBoundingSet=~/)
  assert.match(source, /root-plugin-dropin-backup/)
  assert.match(source, /remove_root_plugin_service\n/)
  assert.doesNotMatch(source, /NOPASSWD:/)
})

test('Windows Stage 2 installs a LocalSystem plugin with guarded lifecycle state', async () => {
  const source = await readFile(windowsInstaller, 'utf8')

  assert.match(source, /netdata-x64\.msi/)
  assert.match(source, /Win32_Service/)
  assert.match(source, /StartName -notin @\('LocalSystem', 'Local System'\)/)
  assert.match(source, /S-1-5-18/)
  assert.match(source, /S-1-5-32-544/)
  assert.match(source, /Join-Path \$env:ProgramData 'WebminAI'/)
  assert.match(source, /webminai\.plugin\.exe/)
  assert.match(source, /Stop-Service -Name Netdata/)
  assert.match(source, /Start-Service -Name Netdata/)
  assert.match(source, /RollbackActivation/)
  assert.match(source, /remove-managed/)
  assert.match(source, /@\('\/qn', '\/x', \$productCode, '\/norestart'\)/)
  assert.doesNotMatch(source, /sudoers|NOPASSWD/)
})
