// Supported library surface. The interactive CLI is intentionally available
// only through bin/intentaiops.js, so importing the library never imports its UI.
export { AdminService } from './admin-service.js'
export { applyApplicationDefaults, FALLBACK_ADMIN_EMAIL, LEGACY_FALLBACK_ADMIN_EMAIL, normalizeAdminEmail, normalizeAdminEmailPreset, normalizeApplicationDefaults } from './application-defaults.js'
export { deploymentBlueprint, validateApplicationDeltaPlan } from './application-delta.js'
export { CodexPlanner } from './codex-planner.js'
export { buildCandidatePlanningContext, buildCommonTask, commonTaskEligibility, isApplicationCommonTask, isLinuxApplicationCommonTask, listCommonTasks, listEligibleCommonTasks } from './common-tasks.js'
export { buildHostHealthTask, hostHealthProfile, isHostHealthTask } from './host-health-task.js'
export { buildSystemUpdateTask, isSystemUpdateTask, systemUpdateProfile } from './system-update-task.js'
export { buildLinuxDockerBootstrapTask } from './linux-docker-bootstrap-task.js'
export { buildFreebsdPodmanBootstrapTask } from './freebsd-podman-bootstrap-task.js'
export { buildN8nTask, n8nRelease } from './n8n-task.js'
export { buildGhostTask, ghostRelease } from './ghost-task.js'
export { buildMattermostTask, mattermostRelease } from './mattermost-task.js'
export { buildOdooTask, odooRelease } from './odoo-task.js'
export { buildJellyfinTask, jellyfinRelease } from './jellyfin-task.js'
export { buildHomeAssistantTask, homeAssistantRelease } from './home-assistant-task.js'
export { CLI_NAME, DATA_DIRECTORY_NAME, LEGACY_DATA_DIRECTORY_NAME, PRODUCT_DOMAIN, PRODUCT_NAME, PRODUCT_TAGLINE, PRODUCT_URL } from './product.js'
export { parseSshConnection, sshTarget } from './connection.js'
export { DEFAULT_KDF, DEFAULT_SCRYPT_KDF, VaultAuthenticationError, argon2Available, createKdfParameters, decryptJson, deriveVaultKey, encryptJson } from './crypto-vault.js'
export { detectNetdataContainer, normalizeDockerPreference, resolveDockerPolicy } from './docker-policy.js'
export { buildDockerComposeProfilePlan } from './docker-compose-profile.js'
export { buildValidationStages } from './canary-scheduler.js'
export { resolveCompatibilityManifest, validateCompatibilityManifest } from './compatibility-manifest.js'
export { buildBaselineCommands, buildDatabasePhase, buildFoundationRevertCommands, buildHttpHealthPhase, buildPackagePhase, buildSafeDiagnosticCommand, buildSecretPhase, buildServicePhase, composeDeploymentPlan, DEPLOYMENT_PHASES } from './deployment-phases.js'
export { annotateVerifiedPlan, buildFoundationPlanningContext, composeFoundationAssistedPlan, composeFoundationPlan, executableFoundationFromCandidates, getDeploymentFoundation, listDeploymentFoundations, validateFoundationSelection } from './deployment-foundations.js'
export { DeploymentScorecard } from './deployment-scorecard.js'
export { formatDiagnosticError, redactDiagnosticText } from './error-details.js'
export { ROOT_EXECUTION_IDENTITY, rootExecutionPolicy } from './execution-policy.js'
export { createKubernetesApiCommand, createSignedCommand, NetdataClient } from './netdata-client.js'
export { parseClaimingInput, validateClaimDetails } from './netdata-claim.js'
export { MultiHostRunStore } from './multi-host-run-store.js'
export { MultiHostService, parallelMap } from './multi-host-service.js'
export { KubernetesApiError, KubernetesClient } from './kubernetes-client.js'
export { KubernetesNetdataClient } from './kubernetes-netdata-client.js'
export { revertNginxValidation, validateNginxFromAllNodes } from './kubernetes-nginx-validation.js'
export { KubernetesStage2Service } from './kubernetes-stage2-service.js'
export { kubernetesCommonTask, listKubernetesCommonTasks } from './kubernetes-common-task-catalog.js'
export { revertKubernetesApplication, validateKubernetesApplication } from './kubernetes-application-validation.js'
export { LinuxHostContextService, parseLinuxExecutionInventory } from './linux-host-context.js'
export { buildLinuxStackProfiles, stackProfileIds, validateLinuxStackProfiles } from './linux-stack-profiles.js'
export { executeApprovedPlan, validateCommandPlan } from './plan-validator.js'
export { PLUGIN_VERSION } from './plugin-version.js'
export { evaluatePromotionEvidence } from './promotion-policy.js'
export { resolveServerDirectory, validateServerId } from './server-id.js'
export { ServerWorkspace } from './server-workspace.js'
export { SettingsStore } from './settings-store.js'
export { parseSshCommand } from './ssh-command.js'
export { Stage2Service } from './stage2-service.js'
export { buildWindowsDockerBootstrapTask, WINDOWS_DOCKER_DESKTOP_RELEASE, WINDOWS_WSL_RELEASE } from './windows-docker-bootstrap-task.js'
export { buildWindowsBraveTask } from './windows-brave-task.js'
export { buildWindowsJoomlaComposeTask } from './windows-joomla-compose-task.js'
export { buildWindowsDrupalComposeTask } from './windows-drupal-compose-task.js'
export { buildWindowsPrestaShopComposeTask } from './windows-prestashop-compose-task.js'
export { buildWindowsN8nComposeTask } from './windows-n8n-compose-task.js'
export { buildWindowsGhostComposeTask } from './windows-ghost-compose-task.js'
export { buildWindowsMattermostComposeTask } from './windows-mattermost-compose-task.js'
export { buildWindowsOdooComposeTask } from './windows-odoo-compose-task.js'
export { buildWindowsJellyfinComposeTask } from './windows-jellyfin-compose-task.js'
export { buildWindowsHomeAssistantComposeTask } from './windows-home-assistant-compose-task.js'
export { SshCommandError, SystemSsh } from './system-ssh.js'
export { TaskStore } from './task-store.js'
